### ISSUE TITLE
"Test connection" gives "Failure"

### ISSUE THREAD

**Issue by predmijat** [kuleuven/jenkins-mattermost-plugin#12]
Hi,

I have both Jenkins and Mattermost set up on my home server.
Both are behind a reverse proxy (NGINX).

My Mattermost URL points to a public IP, and while I'm able to access it from the application, or even to post a message via webhook using `curl`, I can't connect from Jenkins.

I entered webhook URL in "Endpoint" field, tried with no channel name, tried public/private channels, with/without `#` in front of the channel name - I always get "Failure".

My NGINX forces HTTPS (self-signed cert), is that causing the issue? I've tried to install a Jenkins plugin https://wiki.jenkins-ci.org/display/JENKINS/Skip+Certificate+Check+plugin but it didn't help.

Ideas?
Thanks

**Comment by jovandeginste** [comment]
I'm not sure on expected behaviour with self signed certs, and am not able to test at this moment.

Some things you can try:

Allow HTTP - does everything else work then?
Add the self signed certificate to your list of trusted certs in your OS (procedure depends on OS)
Use let's encrypt to get a valid certificate, perhaps by rp'ing through caddy

Depending on the outcome of the above steps, the issue can be pinpointed to SSL and/or the fact that it is self signed...

When I have the ability, I will try to set up a self signed certificate for Mattermost and try to reproduce.

**Comment by predmijat** [comment]
Ok, I'll try that later today (or tomorrow) and report back. I thought that Jenkins' skip cert plugin was enough to discard this as an issue :)

Edit: I've opened Mattermost URL on my home server and it really did show broken HTTPS (I've only added the cert as trusted on my laptop). Then I've created a valid cert using Let's Encrypt (refreshing the page now shows a green padlock), but "Test Connection" in Jenkins still says "Failure"...

**Comment by predmijat** [comment]
Jenkins logs each time I press "Test Connection":

```
Oct 17, 2016 11:18:37 AM INFO jenkins.plugins.mattermost.StandardMattermostService publish
Posting: to (default)@https://URL/hooks/HOOK: Mattermost/Jenkins plugin: you're all set! (parameters: endpoint='https://URL/hooks/HOOK', room='', icon='', buildServerUrl='https://BUILDURL/') (good)
Oct 17, 2016 11:18:37 AM INFO org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
I/O exception (java.net.SocketException) caught when processing request: Connection reset
Oct 17, 2016 11:18:37 AM INFO org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
Retrying request
Oct 17, 2016 11:18:37 AM INFO org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
I/O exception (java.net.SocketException) caught when processing request: Connection reset
Oct 17, 2016 11:18:37 AM INFO org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
Retrying request
Oct 17, 2016 11:18:37 AM INFO org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
I/O exception (java.net.SocketException) caught when processing request: Connection reset
Oct 17, 2016 11:18:37 AM INFO org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
Retrying request
Oct 17, 2016 11:18:37 AM WARNING jenkins.plugins.mattermost.StandardMattermostService publish
Error posting to Mattermost
java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(SocketInputStream.java:196)
    at java.net.SocketInputStream.read(SocketInputStream.java:122)
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
    at sun.security.ssl.InputRecord.read(InputRecord.java:480)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:944)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1342)
    at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:719)
    at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
    at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:506)
    at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
    at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
    at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
    at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
    at jenkins.plugins.mattermost.StandardMattermostService.publish(StandardMattermostService.java:94)
    at jenkins.plugins.mattermost.MattermostNotifier$DescriptorImpl.doTestConnection(MattermostNotifier.java:334)
    at sun.reflect.GeneratedMethodAccessor125.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:324)
    at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:167)
    at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:100)
    at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
    at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
    at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:233)
    at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
    at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
    at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
    at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
    at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
    at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
    at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:499)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
    at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Oct 17, 2016 11:18:37 AM INFO jenkins.plugins.mattermost.StandardMattermostService publish
Posting succeeded
```

**Comment by jovandeginste** [comment]
For clarity, I see `https://URL/hooks/HOOK` but no explanation -- is this you obfuscating the log, or is this really what the log says?

**Comment by predmijat** [comment]
It's me. URL is the one I'm using with `curl` and I know it works.

Additional info:

At the end of the Jenkins log it says "Posting succeeded", but I still get "Failure" in Jenkins to the left of "Test Connection", and there's nothing showing up in Mattermost.

What is the proper way to configure the plugin?
Endpoint: Mattermost webhook URL (the one I use with `curl` when I'm able to get it to post a message)
Channel: Do I need this? Hook is set up for a particular channel, why would I need to enter it manually? If I do need to enter it, do I need `#` in front of the channel name?
Icon to use: Not obligatory I guess
Build Server URL: Already filled up, address is correct

**Comment by jovandeginste** [comment]
For proper configuration, you should have the endpoint and a channel filled; I know you specified a channel when setting up the hook, but my understanding and experience is, that this is not working as expected. You can but don't have to add a `#`, both work. The endpoint url is indeed the full url you use for curl too.

I'm confused by the `connection reset`; is Jenkins running in some kind of container? Can you spawn a shell next to Jenkins and do a `curl` as close to Jenkins as possible? Maybe firewall, maybe the RP (nginx) rejects internal connections, ...?

**Comment by jovandeginste** [comment]
Also, sure-fire configuration would be keep the 'global' configuration empty and only configure these fields at job level (for testing, using a single job).

**Comment by predmijat** [comment]
Jenkins runs as a service, not in a container.
Mattermost however is started using `docker-compose`.

Mattermost URL points to a public IP - I can use `curl` with Mattermost webhook from my laptop, my home server, or from a remote server.

I can connect to Mattermost using mobile application.

I'll try setting things up inside a job configuration.
Edit: same error when ran from inside the job.
Edit 2: I've tried to post to another Mattermost server (HTTP, not HTTPS) from my Jenkins server - again "Failure". Error log is shorter though:

```
Mattermost post may have failed. Response: 
Oct 17, 2016 12:31:58 PM INFO jenkins.plugins.mattermost.StandardMattermostService publish
Posting succeeded
```

Edit 3: I've remembered that I'm running Jenkins on a custom port - can that be an issue?

**Comment by jovandeginste** [comment]
Sorry for the late answer, GitHub does not send notifications on edits... The Jenkins port should not matter: in my setup Mattermost has no access to Jenkins at all.

**Comment by jovandeginste** [comment]
Did you remove the global configuration options for the tests?

**Comment by predmijat** [comment]
Yeah, that's the first edit in previous reply. Still didn't get it work...

**Comment by its02003** [comment]
Just to contribute, I'm seeing similar behavior with the failed posts (could very well be different root causes.)

When I post through CURL, MM works fine, but when I use the Jenkins plugin, no dice. Pulling logs now.

**Comment by its02003** [comment]
Log contents:

INFO: Posting: to MM@http://**our_MM_hosted_server**/hooks/**our_MM_endpoint_name**: **jenkins_project_name** - #5 :white_check_mark: Success after 4 min 2 sec [Open](http://**our_jenkins_server**:8080/job/**jenkins_project_name**/5/) (good)
Nov 09, 2016 2:57:48 PM jenkins.plugins.mattermost.StandardMattermostService publish
WARNING: Mattermost post may have failed. Response:
Nov 09, 2016 2:57:48 PM jenkins.plugins.mattermost.StandardMattermostService publish
INFO: Posting succeeded
Nov 09, 2016 2:57:48 PM jenkins.plugins.mattermost.StandardMattermostService publish
INFO: Posting: to Integration@http://**our_MM_hosted_server**/hooks/**our_MM_endpoint_name**: **jenkins_project_name** - #5 :white_check_mark: Success after 4 min 2 sec [Open](http://**our_jenkins_server**:8080/job/**jenkins_project_name**/5/) (good)
Nov 09, 2016 2:57:48 PM jenkins.plugins.mattermost.StandardMattermostService publish
WARNING: Mattermost post may have failed. Response:
Nov 09, 2016 2:57:48 PM jenkins.plugins.mattermost.StandardMattermostService publish
INFO: Posting succeeded
Nov 09, 2016 2:57:48 PM jenkins.plugins.mattermost.StandardMattermostService publish
INFO: Posting: to Testing@http://**our_MM_hosted_server**/hooks/**our_MM_endpoint_name**: **jenkins_project_name** - #5 :white_check_mark: Success after 4 min 2 sec [Open](http://**our_jenkins_server**:8080/job/**jenkins_project_name**/5/) (good)
Nov 09, 2016 2:57:48 PM jenkins.plugins.mattermost.StandardMattermostService publish
WARNING: Mattermost post may have failed. Response:
Nov 09, 2016 2:57:48 PM jenkins.plugins.mattermost.StandardMattermostService publish
INFO: Posting succeeded

**Comment by its02003** [comment]
I bolded stuff I pulled out

**Comment by jovandeginste** [comment]
Could you tcpdump ?

Met vriendelijke groet,
Jo Vandeginste

**Comment by its02003** [comment]
What specifically are you looking to confirm from the TCPdump?

**Comment by jovandeginste** [comment]
Is the connection happening (and a response returning)? As you are not
using ssl, tcpdump -A may show the actual response. Don't forget to add
filters to tcpdump, you would have too much data otherwise...

**Comment by its02003** [comment]
Locally on my machine, I see communication between my machine and the MM server when using the HTTP API, but when I do similar from the Jenkins server, I'm not seeing anything. Does the system require a full recycle after plugin installation?

**Comment by jovandeginste** [comment]
No restart necessary, but you can always confirm. Do you happen to have
proxy configured in Jenkins?

**Comment by its02003** [comment]
When I say not seeing anything, I mean I see communication between the two systems, but no HTTP data being transferred to/from the service

**Comment by its02003** [comment]
No proxy configured and I have tried with both the job level and global level configurations (removing the other when I try each)

**Comment by jovandeginste** [comment]
Do you see any data transferred? If not HTTP, what then?

Did you use the -A option for tcpdump? (What OS are you hosting Jenkins on?)

> -A     Print each packet (minus its link level header) in ASCII.  Handy for capturing web pages.

**Comment by its02003** [comment]
Duh! I didn't get the packet info...

So, here is what I'm seeing when Jenkins tries to send the "Build Started" notification:

dZ>rÍÊ«ÿPOST /hooks/**endpoint_id** HTTP/1.1
User-Agent: Jakarta Commons-HttpClient/3.1
Host: **our_host**
Content-Length: 744
Content-Type: application/x-www-form-urlencoded

payload=%7B%22icon_url%22%3A%22%22%2C%22attachments%22%3A%5B%7B%22color%22%3A%22danger%22%2C%22mrkdwn_in%22%3A%5B%22pretext%22%2C%22text%22%2C%22fields%22%5D%2C%22fields%22%3A%5B%7B%22short%22%3Afalse%2C%22value%22%3A%22**jenkins_project_id**+-+%239+Started+by+user+**ME**+%5BOpen%5D%28http%3A%2F%2F**jenkins_machine_name**%3A8080%2Fjob%2F**jenkins_project_name**%2F9%2F%29%22%7D%5D%2C%22fallback%22%3A%22**jenkins_project_name**+-+%239+Started+by+user+**ME**+%5BOpen%5D%28http%3A%2F%2F**jenkins_machine_name**%3A8080%2Fjob%2F**jenkins_project_name**%2F9%2F%29%22%7D%5D%2C%22channel%22%3A%22**channel_id**%22%2C%22username%22%3A%22jenkins%22%7D }

I bolded the stuff that had actual proprietary values that I removed

I see this almost immediately after:

ÍÊ«›dZ>rHTTP/1.1 307 Temporary Redirect
Server: nginx/1.6.2
Date: Thu, 10 Nov 2016 13:58:56 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: keep-alive
Content-Security-Policy: frame-ancestors 'none'
Location: /error?title=Mattermost+needs+your+help%3A&message=Couldn%27t+find+the+channel&details=err%3Dstore.sql_channel.get_by_name.missing.app_error&link=%2F&linkmessage=Go+back+to+Mattermost
X-Frame-Options: DENY
X-Request-Id: 5umdqfno4pdbbjjiafoo6ukpay
X-Version-Id: 3.1.0.1474642303

**Comment by jovandeginste** [comment]
Did you enter a channel name or channel id in the Jenkins input field?

**Comment by its02003** [comment]
Just the channel ID

**Comment by its02003** [comment]
Just for completeness, I left the icon field blank.

**Comment by jovandeginste** [comment]
you should enter the channel name like you see it in the url, ie. lowercase and replacing spaces with dashes.

Eg:
`Off-Topic` -> `off-topic`
`Town Square` -> `town-square`

You may or may not prefix the `#`, it is added if not present...

**Comment by its02003** [comment]
That worked! Just so you know, in the help bubble of the Jenkins "Configure System" or "Add post build action" UI, it says the following:

"  
Enter the channel names to which notifications should be sent. Note that this can include names of channels OR channel id numbers, e.g. "#builds", and that multiple values may appear comma separated. While names are more readable, channel ids will not change over time and are therefore more resilient.

This overrides the global setting."

I'm not sure if this is text left over from the Slack code, or if this was just planned functionality which doesn't work yet, but that was what I followed when I used the ID rather than the name.

**Comment by jovandeginste** [comment]
OK, left over from the Slack code... I'll change it asap

**Comment by jovandeginste** [comment]
Fixed in 41af65fdd4ac2012e17e67f1ab431884e6c0af46

@predmijat any solution/update for your problem?

**Comment by predmijat** [comment]
No, kinda got derailed...not sure when/if I'll come back to fix...I was hoping that it would get fixed magically by some update :)

**Comment by jovandeginste** [comment]
OK, I'll close for now, reopen if you have more time and/or input to look into it..

**Comment by predmijat** [comment]
I got the time to do some digging and figured out that my Jenkins setup is the culprit (although I don't know why).

I've tried to post from my Jenkins (running as a service on my home server) to outer Mattermost setup, got `Failure` too.
Then I've tried to post from outer Jenkins setup to my Mattermost (ran via docker-compose on the sam server as my Jenkins), and it succeeded!

In the meantime I've also figured that my Jenkins -> GitLab (also ran inside Docker on my home server) is also broken.

Funny thing is that Jenkins, Mattermost, and GitLab run just fine by themselves, but Jenkins -> MM/GL is broken for some reason. I _think_ it might be something with NGINX reverse proxy setup, but if anyone has any ideas, they are welcome.

**Comment by jovandeginste** [comment]
I can think of many reasons for it to fail, ranging from poorly chosen LAN subnets over firewalls to weird entries in the hosts files. Are you running an outgoing proxy server for Jenkins?

I would start diagnosing from inside the docker containers with telnet, curl, etc, then tcpdump and/or strace the Jenkins PID grepping for `conn` to see where it actually connects to (correct ip, port), using `-A` in grep to see the result from the connection.

**Comment by predmijat** [comment]
There is no outgoing proxy server, but everything is behind reverse proxy.
There is nothing in `hosts` file, I'm pretty sure firewall is not the problem, LAN subnet too...

`telnet` was successful from inside the container to Jenkins.

Job in Jenkins with `ping` to Mattermost URL resolves it fine, `telnet` to Mattermost works, `curl` POST also works.

I wasn't able to find anything useful using `strace` and `tcpdump`, probably because I don't have experience using those :)

Since I've pinpointed the problem to my Jenkins (since I am able to post to Mattermost using other Jenkins), I guess you can close this one (I only see "Comment"). If I ever fix this, I'll try to remember to post the solution here :)

Thanks for your help!

**Comment by jovandeginste** [comment]
No problem - this issue was still closed.

`strace` and `tcpdump` should show you if, when and how Jenkins tries to connect to Mattermost ... I you find nothing from Jenkins to Mattermost, something is very weird :-)

Good luck!

**Comment by predmijat** [comment]
Fixed.

It was OpenJDK 1.7->NGINX SSL config issue.

I had only `ssl_protocols TLSv1.1 TLSv1.2;` in NGINX, which is not supported by OpenJDK 1.7 by default. Adding `TLSv1` made everything work.

Info found here - http://superuser.com/questions/1007662/jenkins-using-jnlp-behind-nginx-ssl-reverse-proxy

Now I need to figure out how to enable TLSv1.2 on OpenJDK 1.7 on Arch :)

edit:
Installing `jdk8-openjdk` and setting it as default environment (on Arch - `archlinux-java set java-8-openjdk`), then restarting Jenkins made it work without TLSv1.

It also made Jenkins->GitLab work (GitLab is running in Docker and has NGINX of its own with new ciphers and what not).
